-- phpMyAdmin SQL Dump
-- version 4.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Erstellungszeit: 13. Jan 2017 um 18:28
-- Server-Version: 10.1.19-MariaDB
-- PHP-Version: 5.6.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Datenbank: `idealist`
--

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle `idea`
--

CREATE TABLE `idea` (
  `ID` int(11) NOT NULL,
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `author` varchar(60) NOT NULL,
  `title` varchar(80) NOT NULL,
  `description` text NOT NULL,
  `comment` text,
  `accepted` tinyint(1) DEFAULT NULL,
  `version` decimal(10,0) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Daten für Tabelle `idea`
--

INSERT INTO `idea` (`ID`, `created`, `updated`, `author`, `title`, `description`, `comment`, `accepted`, `version`) VALUES
(1, '2016-01-06 07:38:15', '0000-00-00 00:00:00', 'Patrick', 'DreamSpark', 'Wie wäre es mit einem Softwareverteilungsportal?', 'Maurice: Gute Idee', 0, '5'),
(2, '2016-01-07 19:48:35', '2016-05-09 09:23:45', 'Thomas', 'Hundezwinger', 'Der Hundezwinger ist ein Gegenstand der zu Verteidigungszwecken errichtet wird.Es handelt sich um einen Käfig, der 4 Kampfhunde enthält. Die Hunde greifen automatisch an, wenn sich feindliche Einheiten in der Nähe befinden und kehren danach in den Käfig zurück. In Stronghold Crusader greifen sie nur feindliche Einheiten an. ', 'Stefan: Wir haben einen Hundezwinger im Garten stehen. Wenn wir mal für längere Zeit weg sind über den Tag dann kommt unser Hund da rein. Der Zwinger ist groß und sein Hundehaus passt da auch gut rein. \r\nMissbrauch melden.', 1, '66'),
(3, '2016-01-12 12:27:06', '2016-08-23 12:36:00', 'Stefan', 'Römische Mythologie', 'Personen aus der Römischen Mythologie:', 'Lucifer wird als Vorreiter des Helios gesehen, wobei sein Pferd bisweilen entsprechend der Tageszeit die Farbe wechselt[1] oder er fährt wie dieser im Wagen über den Himmel. ...', 0, '420'),
(4, '2016-01-13 16:48:28', '2016-10-22 13:25:33', 'Stefan', 'Bundeskanzlerin', 'Wie heißt unsere aktuelle Kanzlerin?', 'Angela Merkel wurde am 22. November 2005 zur Bundeskanzlerin gewählt. Die erste Frau und Naturwissenschaftlerin, die das höchste Regierungsamt Deutschlands bekleidet, stützte sich auf eine große Koalition aus CDU/CSU und SPD. Bei Amtsantritt war sie mit 51 Jahren die jüngste Amtsinhaberin, ist die erste ehemalige Bürgerin der DDR als gesamtdeutsche Kanzlerin und nach der Wende Quereinsteigerin aus der Wissenschaft in die Politik.', 1, '2763'),
(5, '2016-01-15 08:56:23', '2016-04-02 21:59:47', 'Tim', 'Innovationsmanagment', 'Die Definition von Innovationsmanagment.', 'Innovationsmanagement ist die systematische Planung, Steuerung und Kontrolle von Innovationen in Organisationen. Im Unterschied zu Kreativität, die sich mit der Entwicklung von Ideen beschäftigt, ist Innovationsmanagement auch auf die Verwertung von Ideen bzw. deren Umsetzung in wirtschaftlich erfolgreiche Produkte bzw. Dienstleistungen ausgerichtet.', 0, '123'),
(6, '2016-01-19 10:23:34', '2016-06-15 19:59:16', 'Patrick', 'Tentorium ', 'Erklärung', 'Das Tentorium ist eine innere Skelettstruktur im Kopf der Insekten, der übrigen Hexapoda (Entognatha) und der Tausendfüßer. Es entsteht aus fingerförmigen Einstülpungen des Exoskeletts, die generell Apodeme genannt werden. Diese sog. Tentoriumsäste können im Kopfinnern frei bleiben oder sich zu einer gemeinsamen Struktur vereinigen. Aufgabe des Tentoriums ist die innere Versteifung der hohlen Kopfkapsel gegen mechanische Beanspruchungen, wie sie z. B. aus der Arbeit der Mundwerkzeuge entstehen können. Außerdem dient die Struktur als Ansatzpunkt und Widerlager für zahlreiche Muskeln. Da das Tentorium aus einer Einstülpung der Kopfkapsel nach innen entsteht, ist seine Ansatzstelle außen meist in Form einer kleinen Einsenkung sichtbar, die Tentoriumsgrube genannt wird. Durch die vier Äste ergeben sich zwei vordere und zwei hintere Tentoriumsgruben. Diese liegen in der Regel innerhalb von Kopfnähten. Ihre Lage ist bei verschiedenen Insektenordnungen unterschiedlich.', 1, '78'),
(7, '2016-01-20 11:12:12', '2016-02-02 22:59:38', 'Tim', 'Werkblei', 'Werkblei ist noch unreines Rohblei, welches sich während des Verhüttungsprozesses im unteren Teil des Ofens ansammelt und bis zu 5 % Verunreinigungen wie Kupfer, Zinn, Antimon, Arsen, Bismut oder Edelmetalle wie Silber und Gold in wechselnden Anteilen enthält. Hierbei wird die silberreiche Legierung Güldischsilber genannt.', 'Das Werkblei verlässt mit ca. 900 bis 1000 °C den Ofen und scheidet bereits beim Abkühlen die Verunreinigungen aus, die bei niedrigeren Temperaturen im Blei schlecht löslich sind. Diese werden als Schlicker abgezogen und entweder in den Ofen zurückgegeben oder separat aufgearbeitet.\r\nDas Werkblei hat je nach Hütte unterschiedliche Zusammensetzung, kommt in der Regel nicht in den Handel, sondern wird weiter raffiniert zu Hüttenblei oder Feinblei.', 0, '99'),
(8, '2016-01-23 22:01:55', '2016-06-09 19:59:08', 'Patrick', 'Parthenophilie', 'Parthenophilie (altgr. παρθένος parthénos „Jungfrau“ und -philie) beschreibt das erotisch-sexuelle Interesse Erwachsener an pubertären Mädchen.', 'Diese Neigung ist aus sexualwissenschaftlicher Sicht von der Pädophilie abzugrenzen, bei der sich das begehrte Objekt im präpubertären Stadium befindet. Der Begriff „Parthenophilie“ wurde lange Zeit nur sehr selten verwendet, gewinnt aber mit der Beschäftigung um den Themenbereich sexueller Missbrauch und der damit einhergehenden genaueren Differenzierung wieder an Bedeutung.\r\nDer Begriff wurde von Magnus Hirschfeld geprägt und erschien erstmals 1906 in dessen Werk Vom Wesen der Liebe. Er wird dort dem Begriff Ephebophilie beigestellt, welcher das erotisch-sexuelle Interesse an pubertierenden Jungen ausdrückt.[1] In seinem Werk Die Homosexualität des Mannes und des Weibes aus dem Jahre 1914 stellt er ein ganzes Begriffssystem vor und beschreibt das Alter vom Beginn bis zum Abschluss der körperlichen Reifung.[2] Beier, Bosinski und Loewit beschreiben unter „Differenzialtypologie dissexuellen Verhaltens“ einen Altersbereich von zirka 12 bis 17 Jahren, wobei sich die weiblichen Kinder und Jugendlichen bereits mindestens in der ersten Phase der körperlichen Sexualentwicklung (beginnende Schambehaarung) befinden. Sie merken ebenfalls an, dass auch ältere junge Frauen attraktiv sein können, sofern sie dem jugendlichen Typus entsprechen, sowie auch Mädchen, die bereits mit elf oder zwölf Jahren in die Pubertät eintreten.[3] Im Gegensatz zur Pädophilie stelle die Parthenophilie „eine sexualbiologisch erwartbare Reaktion“ dar und könne nicht als „Störung der sexuellen Präferenz kategorisiert werden“.', 1, '23'),
(9, '2016-01-25 17:23:36', '2016-08-31 21:59:21', 'Stefan', 'Hahnkampl', 'Das Hahnkampl ist ein 2080 m ü. A. hoher Berg in der Sonnjochgruppe im Karwendel in Tirol.', 'Der Gipfel ist als unschwierige Bergwanderung von der Eng über die Binsalm und den Binssattel zu erreichen (vom Alpengasthof Eng: Aufstiegszeit (über Binssattel): ca. 2:15 Stunden, Abstiegszeit (über Lamsenjoch): ca. 2:00 Stunden, ca. 880 Höhenmeter). Alternativ ist der Gipfel vom Falzthurntal über den Gramaialm-Hochleger (1756 m ü. A.) zu erreichen. Die Gipfelüberschreitung mit dem Abstieg zum Westlichen Lamsenjoch (1940 m ü. A.) erfordert Trittsicherheit und Schwindelfreiheit.', 0, '11'),
(10, '2016-01-29 04:19:35', '2017-01-09 20:59:25', 'Maurice', 'Werft', 'Eine Werft (alt-niederl./friesl.: Der am Wasser baut, siehe auch: Warft) ist ein Betrieb zum Bau und zur Reparatur von Booten und Schiffen.', 'Bis Anfang des 20. Jahrhunderts wurde als die oder das Werft auch ein Flussufer bezeichnet, das für den Handel, Reparatur und Bau von Schiffen eingerichtet war.[1]\r\nMit der einsetzenden Entwicklung großer Luftschiffe und Flugzeuge wurde der Begriff Werft auch auf Anlagen zur Produktion und Grundinstandsetzung im Luftschiffbau (Luftschiffwerft) und Flugzeugbau (Flugzeugwerft) übertragen.\r\nDer klassische Schiffbauplatz einer Werft ist die Helling oder der Helgen. Heutzutage werden Schiffe auf vielen Werften auf überdachten Bauplätzen oder in einer Schiffbauhalle, teilweise in überdachten oder geschützten Baudocks gebaut.\r\nJedes Schiff erhält bei Baubeginn eine Bau-Nr. (Baunummer). Dies ist meist eine fortlaufende Zahl, welche die jeweilige Anzahl der bisher auf der Werft gebauten Schiffe angibt. Es gibt aber auch Werften, die zum Beispiel bei jeweils verschiedenen Bauserien analog auch neue Baunummernblöcke beginnen.\r\nNeben dem Bau werden von Werften ebenso Reparaturen und Umbauten sowie Instandhaltungsmaßnahmen an Schiffen durchgeführt. Auch dabei müssen Schiffe oft in Schwimm- oder Trockendocks trockengelegt werden, sofern bei kleineren Fahrzeugen hierfür nicht Slipanlagen oder Kräne eingesetzt werden.\r\nWerftbetriebe sind zumeist auf bestimmte Arten von Schiffen und Booten ausgerichtet. So wird nach den Typen von Wasserfahrzeugen unterschieden zwischen\r\nBootswerften – für kleinere Fahrzeuge\r\nBinnenschiffswerften – für Binnenschiffe\r\nSeeschiffswerften – für Seeschiffe\r\nDiese sind zum Teil wiederum auf spezielle Schiffstypen spezialisiert. Auch kann der Schwerpunkt der Tätigkeit einer Werft ganz oder teilweise in den Bereichen Bau, Reparatur, Wartung oder Umbau liegen.\r\nDiese Aufgaben werden für Kriegsschiffe zum Teil in Marinearsenalen ausgeführt.\r\nDie Zerlegung von Schiffen erfolgt oft in darauf spezialisierten Abwrackwerften.', 1, '65'),
(11, '2016-02-06 07:38:15', '2016-03-31 21:59:33', 'Patrick', 'DreamSpark', 'Wie wäre es mit einem Softwareverteilungsportal?', 'Maurice: Gute Idee', 0, '5'),
(12, '2016-02-07 19:48:35', '2016-04-09 09:23:45', 'Thomas', 'Hundezwinger', 'Der Hundezwinger ist ein Gegenstand der zu Verteidigungszwecken errichtet wird.Es handelt sich um einen Käfig, der 4 Kampfhunde enthält. Die Hunde greifen automatisch an, wenn sich feindliche Einheiten in der Nähe befinden und kehren danach in den Käfig zurück. In Stronghold Crusader greifen sie nur feindliche Einheiten an. ', 'Stefan: Wir haben einen Hundezwinger im Garten stehen. Wenn wir mal für längere Zeit weg sind über den Tag dann kommt unser Hund da rein. Der Zwinger ist groß und sein Hundehaus passt da auch gut rein. \r\nMissbrauch melden.', 1, '66'),
(13, '2016-02-12 12:27:06', '2016-07-23 12:36:00', 'Stefan', 'Römische Mythologie', 'Personen aus der Römischen Mythologie:', 'Lucifer wird als Vorreiter des Helios gesehen, wobei sein Pferd bisweilen entsprechend der Tageszeit die Farbe wechselt[1] oder er fährt wie dieser im Wagen über den Himmel. ...', 0, '420'),
(14, '2016-02-13 16:48:28', '2016-11-22 14:25:33', 'Stefan', 'Bundeskanzlerin', 'Wie heißt unsere aktuelle Kanzlerin?', 'Angela Merkel wurde am 22. November 2005 zur Bundeskanzlerin gewählt. Die erste Frau und Naturwissenschaftlerin, die das höchste Regierungsamt Deutschlands bekleidet, stützte sich auf eine große Koalition aus CDU/CSU und SPD. Bei Amtsantritt war sie mit 51 Jahren die jüngste Amtsinhaberin, ist die erste ehemalige Bürgerin der DDR als gesamtdeutsche Kanzlerin und nach der Wende Quereinsteigerin aus der Wissenschaft in die Politik.', 1, '2763'),
(15, '2016-02-15 08:56:23', '2016-05-02 21:59:47', 'Tim', 'Innovationsmanagment', 'Die Definition von Innovationsmanagment.', 'Innovationsmanagement ist die systematische Planung, Steuerung und Kontrolle von Innovationen in Organisationen. Im Unterschied zu Kreativität, die sich mit der Entwicklung von Ideen beschäftigt, ist Innovationsmanagement auch auf die Verwertung von Ideen bzw. deren Umsetzung in wirtschaftlich erfolgreiche Produkte bzw. Dienstleistungen ausgerichtet.', 0, '123'),
(16, '2016-02-19 10:23:34', '2016-07-15 19:59:16', 'Patrick', 'Tentorium ', 'Erklärung', 'Das Tentorium ist eine innere Skelettstruktur im Kopf der Insekten, der übrigen Hexapoda (Entognatha) und der Tausendfüßer. Es entsteht aus fingerförmigen Einstülpungen des Exoskeletts, die generell Apodeme genannt werden. Diese sog. Tentoriumsäste können im Kopfinnern frei bleiben oder sich zu einer gemeinsamen Struktur vereinigen. Aufgabe des Tentoriums ist die innere Versteifung der hohlen Kopfkapsel gegen mechanische Beanspruchungen, wie sie z. B. aus der Arbeit der Mundwerkzeuge entstehen können. Außerdem dient die Struktur als Ansatzpunkt und Widerlager für zahlreiche Muskeln. Da das Tentorium aus einer Einstülpung der Kopfkapsel nach innen entsteht, ist seine Ansatzstelle außen meist in Form einer kleinen Einsenkung sichtbar, die Tentoriumsgrube genannt wird. Durch die vier Äste ergeben sich zwei vordere und zwei hintere Tentoriumsgruben. Diese liegen in der Regel innerhalb von Kopfnähten. Ihre Lage ist bei verschiedenen Insektenordnungen unterschiedlich.', 1, '78'),
(17, '2016-02-20 11:12:12', '2016-06-02 21:59:38', 'Tim', 'Werkblei', 'Werkblei ist noch unreines Rohblei, welches sich während des Verhüttungsprozesses im unteren Teil des Ofens ansammelt und bis zu 5 % Verunreinigungen wie Kupfer, Zinn, Antimon, Arsen, Bismut oder Edelmetalle wie Silber und Gold in wechselnden Anteilen enthält. Hierbei wird die silberreiche Legierung Güldischsilber genannt.', 'Das Werkblei verlässt mit ca. 900 bis 1000 °C den Ofen und scheidet bereits beim Abkühlen die Verunreinigungen aus, die bei niedrigeren Temperaturen im Blei schlecht löslich sind. Diese werden als Schlicker abgezogen und entweder in den Ofen zurückgegeben oder separat aufgearbeitet.\r\nDas Werkblei hat je nach Hütte unterschiedliche Zusammensetzung, kommt in der Regel nicht in den Handel, sondern wird weiter raffiniert zu Hüttenblei oder Feinblei.', 0, '99'),
(18, '2016-02-23 22:01:55', '2016-05-09 19:59:08', 'Patrick', 'Parthenophilie', 'Parthenophilie (altgr. παρθένος parthénos „Jungfrau“ und -philie) beschreibt das erotisch-sexuelle Interesse Erwachsener an pubertären Mädchen.', 'Diese Neigung ist aus sexualwissenschaftlicher Sicht von der Pädophilie abzugrenzen, bei der sich das begehrte Objekt im präpubertären Stadium befindet. Der Begriff „Parthenophilie“ wurde lange Zeit nur sehr selten verwendet, gewinnt aber mit der Beschäftigung um den Themenbereich sexueller Missbrauch und der damit einhergehenden genaueren Differenzierung wieder an Bedeutung.\r\nDer Begriff wurde von Magnus Hirschfeld geprägt und erschien erstmals 1906 in dessen Werk Vom Wesen der Liebe. Er wird dort dem Begriff Ephebophilie beigestellt, welcher das erotisch-sexuelle Interesse an pubertierenden Jungen ausdrückt.[1] In seinem Werk Die Homosexualität des Mannes und des Weibes aus dem Jahre 1914 stellt er ein ganzes Begriffssystem vor und beschreibt das Alter vom Beginn bis zum Abschluss der körperlichen Reifung.[2] Beier, Bosinski und Loewit beschreiben unter „Differenzialtypologie dissexuellen Verhaltens“ einen Altersbereich von zirka 12 bis 17 Jahren, wobei sich die weiblichen Kinder und Jugendlichen bereits mindestens in der ersten Phase der körperlichen Sexualentwicklung (beginnende Schambehaarung) befinden. Sie merken ebenfalls an, dass auch ältere junge Frauen attraktiv sein können, sofern sie dem jugendlichen Typus entsprechen, sowie auch Mädchen, die bereits mit elf oder zwölf Jahren in die Pubertät eintreten.[3] Im Gegensatz zur Pädophilie stelle die Parthenophilie „eine sexualbiologisch erwartbare Reaktion“ dar und könne nicht als „Störung der sexuellen Präferenz kategorisiert werden“.', 1, '23'),
(19, '2016-02-25 17:23:36', '0000-00-00 00:00:00', 'Stefan', 'Hahnkampl', 'Das Hahnkampl ist ein 2080 m ü. A. hoher Berg in der Sonnjochgruppe im Karwendel in Tirol.', 'Der Gipfel ist als unschwierige Bergwanderung von der Eng über die Binsalm und den Binssattel zu erreichen (vom Alpengasthof Eng: Aufstiegszeit (über Binssattel): ca. 2:15 Stunden, Abstiegszeit (über Lamsenjoch): ca. 2:00 Stunden, ca. 880 Höhenmeter). Alternativ ist der Gipfel vom Falzthurntal über den Gramaialm-Hochleger (1756 m ü. A.) zu erreichen. Die Gipfelüberschreitung mit dem Abstieg zum Westlichen Lamsenjoch (1940 m ü. A.) erfordert Trittsicherheit und Schwindelfreiheit.', 0, '11'),
(20, '2016-02-29 04:19:35', '2017-06-09 19:59:25', 'Maurice', 'Werft', 'Eine Werft (alt-niederl./friesl.: Der am Wasser baut, siehe auch: Warft) ist ein Betrieb zum Bau und zur Reparatur von Booten und Schiffen.', 'Bis Anfang des 20. Jahrhunderts wurde als die oder das Werft auch ein Flussufer bezeichnet, das für den Handel, Reparatur und Bau von Schiffen eingerichtet war.[1]\r\nMit der einsetzenden Entwicklung großer Luftschiffe und Flugzeuge wurde der Begriff Werft auch auf Anlagen zur Produktion und Grundinstandsetzung im Luftschiffbau (Luftschiffwerft) und Flugzeugbau (Flugzeugwerft) übertragen.\r\nDer klassische Schiffbauplatz einer Werft ist die Helling oder der Helgen. Heutzutage werden Schiffe auf vielen Werften auf überdachten Bauplätzen oder in einer Schiffbauhalle, teilweise in überdachten oder geschützten Baudocks gebaut.\r\nJedes Schiff erhält bei Baubeginn eine Bau-Nr. (Baunummer). Dies ist meist eine fortlaufende Zahl, welche die jeweilige Anzahl der bisher auf der Werft gebauten Schiffe angibt. Es gibt aber auch Werften, die zum Beispiel bei jeweils verschiedenen Bauserien analog auch neue Baunummernblöcke beginnen.\r\nNeben dem Bau werden von Werften ebenso Reparaturen und Umbauten sowie Instandhaltungsmaßnahmen an Schiffen durchgeführt. Auch dabei müssen Schiffe oft in Schwimm- oder Trockendocks trockengelegt werden, sofern bei kleineren Fahrzeugen hierfür nicht Slipanlagen oder Kräne eingesetzt werden.\r\nWerftbetriebe sind zumeist auf bestimmte Arten von Schiffen und Booten ausgerichtet. So wird nach den Typen von Wasserfahrzeugen unterschieden zwischen\r\nBootswerften – für kleinere Fahrzeuge\r\nBinnenschiffswerften – für Binnenschiffe\r\nSeeschiffswerften – für Seeschiffe\r\nDiese sind zum Teil wiederum auf spezielle Schiffstypen spezialisiert. Auch kann der Schwerpunkt der Tätigkeit einer Werft ganz oder teilweise in den Bereichen Bau, Reparatur, Wartung oder Umbau liegen.\r\nDiese Aufgaben werden für Kriegsschiffe zum Teil in Marinearsenalen ausgeführt.\r\nDie Zerlegung von Schiffen erfolgt oft in darauf spezialisierten Abwrackwerften.', 1, '65'),
(21, '2016-03-06 07:38:15', '2016-12-31 22:59:33', 'Patrick', 'DreamSpark', 'Wie wäre es mit einem Softwareverteilungsportal?', 'Maurice: Gute Idee', 0, '5'),
(22, '2016-03-07 19:48:35', '2016-07-09 09:23:45', 'Thomas', 'Hundezwinger', 'Der Hundezwinger ist ein Gegenstand der zu Verteidigungszwecken errichtet wird.Es handelt sich um einen Käfig, der 4 Kampfhunde enthält. Die Hunde greifen automatisch an, wenn sich feindliche Einheiten in der Nähe befinden und kehren danach in den Käfig zurück. In Stronghold Crusader greifen sie nur feindliche Einheiten an. ', 'Stefan: Wir haben einen Hundezwinger im Garten stehen. Wenn wir mal für längere Zeit weg sind über den Tag dann kommt unser Hund da rein. Der Zwinger ist groß und sein Hundehaus passt da auch gut rein. \r\nMissbrauch melden.', 1, '66'),
(23, '2016-03-12 12:27:06', '2016-09-23 12:36:00', 'Stefan', 'Römische Mythologie', 'Personen aus der Römischen Mythologie:', 'Lucifer wird als Vorreiter des Helios gesehen, wobei sein Pferd bisweilen entsprechend der Tageszeit die Farbe wechselt[1] oder er fährt wie dieser im Wagen über den Himmel. ...', 0, '420'),
(24, '2016-03-13 16:48:28', '2016-11-22 14:25:33', 'Stefan', 'Bundeskanzlerin', 'Wie heißt unsere aktuelle Kanzlerin?', 'Angela Merkel wurde am 22. November 2005 zur Bundeskanzlerin gewählt. Die erste Frau und Naturwissenschaftlerin, die das höchste Regierungsamt Deutschlands bekleidet, stützte sich auf eine große Koalition aus CDU/CSU und SPD. Bei Amtsantritt war sie mit 51 Jahren die jüngste Amtsinhaberin, ist die erste ehemalige Bürgerin der DDR als gesamtdeutsche Kanzlerin und nach der Wende Quereinsteigerin aus der Wissenschaft in die Politik.', 1, '2763'),
(25, '2016-03-15 08:56:23', '2016-09-02 21:59:47', 'Tim', 'Innovationsmanagment', 'Die Definition von Innovationsmanagment.', 'Innovationsmanagement ist die systematische Planung, Steuerung und Kontrolle von Innovationen in Organisationen. Im Unterschied zu Kreativität, die sich mit der Entwicklung von Ideen beschäftigt, ist Innovationsmanagement auch auf die Verwertung von Ideen bzw. deren Umsetzung in wirtschaftlich erfolgreiche Produkte bzw. Dienstleistungen ausgerichtet.', 0, '123'),
(26, '2016-03-19 10:23:34', '2016-07-15 19:59:16', 'Patrick', 'Tentorium ', 'Erklärung', 'Das Tentorium ist eine innere Skelettstruktur im Kopf der Insekten, der übrigen Hexapoda (Entognatha) und der Tausendfüßer. Es entsteht aus fingerförmigen Einstülpungen des Exoskeletts, die generell Apodeme genannt werden. Diese sog. Tentoriumsäste können im Kopfinnern frei bleiben oder sich zu einer gemeinsamen Struktur vereinigen. Aufgabe des Tentoriums ist die innere Versteifung der hohlen Kopfkapsel gegen mechanische Beanspruchungen, wie sie z. B. aus der Arbeit der Mundwerkzeuge entstehen können. Außerdem dient die Struktur als Ansatzpunkt und Widerlager für zahlreiche Muskeln. Da das Tentorium aus einer Einstülpung der Kopfkapsel nach innen entsteht, ist seine Ansatzstelle außen meist in Form einer kleinen Einsenkung sichtbar, die Tentoriumsgrube genannt wird. Durch die vier Äste ergeben sich zwei vordere und zwei hintere Tentoriumsgruben. Diese liegen in der Regel innerhalb von Kopfnähten. Ihre Lage ist bei verschiedenen Insektenordnungen unterschiedlich.', 1, '78'),
(27, '2016-03-20 11:12:12', '2016-06-02 21:59:38', 'Tim', 'Werkblei', 'Werkblei ist noch unreines Rohblei, welches sich während des Verhüttungsprozesses im unteren Teil des Ofens ansammelt und bis zu 5 % Verunreinigungen wie Kupfer, Zinn, Antimon, Arsen, Bismut oder Edelmetalle wie Silber und Gold in wechselnden Anteilen enthält. Hierbei wird die silberreiche Legierung Güldischsilber genannt.', 'Das Werkblei verlässt mit ca. 900 bis 1000 °C den Ofen und scheidet bereits beim Abkühlen die Verunreinigungen aus, die bei niedrigeren Temperaturen im Blei schlecht löslich sind. Diese werden als Schlicker abgezogen und entweder in den Ofen zurückgegeben oder separat aufgearbeitet.\r\nDas Werkblei hat je nach Hütte unterschiedliche Zusammensetzung, kommt in der Regel nicht in den Handel, sondern wird weiter raffiniert zu Hüttenblei oder Feinblei.', 0, '99'),
(28, '2016-03-23 22:01:55', '2016-05-09 19:59:08', 'Patrick', 'Parthenophilie', 'Parthenophilie (altgr. παρθένος parthénos „Jungfrau“ und -philie) beschreibt das erotisch-sexuelle Interesse Erwachsener an pubertären Mädchen.', 'Diese Neigung ist aus sexualwissenschaftlicher Sicht von der Pädophilie abzugrenzen, bei der sich das begehrte Objekt im präpubertären Stadium befindet. Der Begriff „Parthenophilie“ wurde lange Zeit nur sehr selten verwendet, gewinnt aber mit der Beschäftigung um den Themenbereich sexueller Missbrauch und der damit einhergehenden genaueren Differenzierung wieder an Bedeutung.\r\nDer Begriff wurde von Magnus Hirschfeld geprägt und erschien erstmals 1906 in dessen Werk Vom Wesen der Liebe. Er wird dort dem Begriff Ephebophilie beigestellt, welcher das erotisch-sexuelle Interesse an pubertierenden Jungen ausdrückt.[1] In seinem Werk Die Homosexualität des Mannes und des Weibes aus dem Jahre 1914 stellt er ein ganzes Begriffssystem vor und beschreibt das Alter vom Beginn bis zum Abschluss der körperlichen Reifung.[2] Beier, Bosinski und Loewit beschreiben unter „Differenzialtypologie dissexuellen Verhaltens“ einen Altersbereich von zirka 12 bis 17 Jahren, wobei sich die weiblichen Kinder und Jugendlichen bereits mindestens in der ersten Phase der körperlichen Sexualentwicklung (beginnende Schambehaarung) befinden. Sie merken ebenfalls an, dass auch ältere junge Frauen attraktiv sein können, sofern sie dem jugendlichen Typus entsprechen, sowie auch Mädchen, die bereits mit elf oder zwölf Jahren in die Pubertät eintreten.[3] Im Gegensatz zur Pädophilie stelle die Parthenophilie „eine sexualbiologisch erwartbare Reaktion“ dar und könne nicht als „Störung der sexuellen Präferenz kategorisiert werden“.', 1, '23'),
(29, '2016-03-25 17:23:36', '2016-10-31 22:59:21', 'Stefan', 'Hahnkampl', 'Das Hahnkampl ist ein 2080 m ü. A. hoher Berg in der Sonnjochgruppe im Karwendel in Tirol.', 'Der Gipfel ist als unschwierige Bergwanderung von der Eng über die Binsalm und den Binssattel zu erreichen (vom Alpengasthof Eng: Aufstiegszeit (über Binssattel): ca. 2:15 Stunden, Abstiegszeit (über Lamsenjoch): ca. 2:00 Stunden, ca. 880 Höhenmeter). Alternativ ist der Gipfel vom Falzthurntal über den Gramaialm-Hochleger (1756 m ü. A.) zu erreichen. Die Gipfelüberschreitung mit dem Abstieg zum Westlichen Lamsenjoch (1940 m ü. A.) erfordert Trittsicherheit und Schwindelfreiheit.', 0, '11'),
(30, '2016-03-29 03:19:35', '2017-09-09 19:59:25', 'Maurice', 'Werft', 'Eine Werft (alt-niederl./friesl.: Der am Wasser baut, siehe auch: Warft) ist ein Betrieb zum Bau und zur Reparatur von Booten und Schiffen.', 'Bis Anfang des 20. Jahrhunderts wurde als die oder das Werft auch ein Flussufer bezeichnet, das für den Handel, Reparatur und Bau von Schiffen eingerichtet war.[1]\r\nMit der einsetzenden Entwicklung großer Luftschiffe und Flugzeuge wurde der Begriff Werft auch auf Anlagen zur Produktion und Grundinstandsetzung im Luftschiffbau (Luftschiffwerft) und Flugzeugbau (Flugzeugwerft) übertragen.\r\nDer klassische Schiffbauplatz einer Werft ist die Helling oder der Helgen. Heutzutage werden Schiffe auf vielen Werften auf überdachten Bauplätzen oder in einer Schiffbauhalle, teilweise in überdachten oder geschützten Baudocks gebaut.\r\nJedes Schiff erhält bei Baubeginn eine Bau-Nr. (Baunummer). Dies ist meist eine fortlaufende Zahl, welche die jeweilige Anzahl der bisher auf der Werft gebauten Schiffe angibt. Es gibt aber auch Werften, die zum Beispiel bei jeweils verschiedenen Bauserien analog auch neue Baunummernblöcke beginnen.\r\nNeben dem Bau werden von Werften ebenso Reparaturen und Umbauten sowie Instandhaltungsmaßnahmen an Schiffen durchgeführt. Auch dabei müssen Schiffe oft in Schwimm- oder Trockendocks trockengelegt werden, sofern bei kleineren Fahrzeugen hierfür nicht Slipanlagen oder Kräne eingesetzt werden.\r\nWerftbetriebe sind zumeist auf bestimmte Arten von Schiffen und Booten ausgerichtet. So wird nach den Typen von Wasserfahrzeugen unterschieden zwischen\r\nBootswerften – für kleinere Fahrzeuge\r\nBinnenschiffswerften – für Binnenschiffe\r\nSeeschiffswerften – für Seeschiffe\r\nDiese sind zum Teil wiederum auf spezielle Schiffstypen spezialisiert. Auch kann der Schwerpunkt der Tätigkeit einer Werft ganz oder teilweise in den Bereichen Bau, Reparatur, Wartung oder Umbau liegen.\r\nDiese Aufgaben werden für Kriegsschiffe zum Teil in Marinearsenalen ausgeführt.\r\nDie Zerlegung von Schiffen erfolgt oft in darauf spezialisierten Abwrackwerften.', 1, '65'),
(31, '2016-04-06 06:38:15', '0000-00-00 00:00:00', 'Patrick', 'DreamSpark', 'Wie wäre es mit einem Softwareverteilungsportal?', 'Maurice: Gute Idee', 0, '5'),
(32, '2016-04-07 18:48:35', '2016-12-09 10:23:45', 'Thomas', 'Hundezwinger', 'Der Hundezwinger ist ein Gegenstand der zu Verteidigungszwecken errichtet wird.Es handelt sich um einen Käfig, der 4 Kampfhunde enthält. Die Hunde greifen automatisch an, wenn sich feindliche Einheiten in der Nähe befinden und kehren danach in den Käfig zurück. In Stronghold Crusader greifen sie nur feindliche Einheiten an. ', 'Stefan: Wir haben einen Hundezwinger im Garten stehen. Wenn wir mal für längere Zeit weg sind über den Tag dann kommt unser Hund da rein. Der Zwinger ist groß und sein Hundehaus passt da auch gut rein. \r\nMissbrauch melden.', 1, '66'),
(33, '2016-04-12 11:27:06', '2016-10-23 12:36:00', 'Stefan', 'Römische Mythologie', 'Personen aus der Römischen Mythologie:', 'Lucifer wird als Vorreiter des Helios gesehen, wobei sein Pferd bisweilen entsprechend der Tageszeit die Farbe wechselt[1] oder er fährt wie dieser im Wagen über den Himmel. ...', 0, '420'),
(34, '2016-04-13 15:48:28', '2016-11-22 14:25:33', 'Stefan', 'Bundeskanzlerin', 'Wie heißt unsere aktuelle Kanzlerin?', 'Angela Merkel wurde am 22. November 2005 zur Bundeskanzlerin gewählt. Die erste Frau und Naturwissenschaftlerin, die das höchste Regierungsamt Deutschlands bekleidet, stützte sich auf eine große Koalition aus CDU/CSU und SPD. Bei Amtsantritt war sie mit 51 Jahren die jüngste Amtsinhaberin, ist die erste ehemalige Bürgerin der DDR als gesamtdeutsche Kanzlerin und nach der Wende Quereinsteigerin aus der Wissenschaft in die Politik.', 1, '2763'),
(35, '2016-04-15 07:56:23', '2016-08-02 21:59:47', 'Tim', 'Innovationsmanagment', 'Die Definition von Innovationsmanagment.', 'Innovationsmanagement ist die systematische Planung, Steuerung und Kontrolle von Innovationen in Organisationen. Im Unterschied zu Kreativität, die sich mit der Entwicklung von Ideen beschäftigt, ist Innovationsmanagement auch auf die Verwertung von Ideen bzw. deren Umsetzung in wirtschaftlich erfolgreiche Produkte bzw. Dienstleistungen ausgerichtet.', 0, '123'),
(36, '2016-04-19 09:23:34', '2016-11-15 20:59:16', 'Patrick', 'Tentorium ', 'Erklärung', 'Das Tentorium ist eine innere Skelettstruktur im Kopf der Insekten, der übrigen Hexapoda (Entognatha) und der Tausendfüßer. Es entsteht aus fingerförmigen Einstülpungen des Exoskeletts, die generell Apodeme genannt werden. Diese sog. Tentoriumsäste können im Kopfinnern frei bleiben oder sich zu einer gemeinsamen Struktur vereinigen. Aufgabe des Tentoriums ist die innere Versteifung der hohlen Kopfkapsel gegen mechanische Beanspruchungen, wie sie z. B. aus der Arbeit der Mundwerkzeuge entstehen können. Außerdem dient die Struktur als Ansatzpunkt und Widerlager für zahlreiche Muskeln. Da das Tentorium aus einer Einstülpung der Kopfkapsel nach innen entsteht, ist seine Ansatzstelle außen meist in Form einer kleinen Einsenkung sichtbar, die Tentoriumsgrube genannt wird. Durch die vier Äste ergeben sich zwei vordere und zwei hintere Tentoriumsgruben. Diese liegen in der Regel innerhalb von Kopfnähten. Ihre Lage ist bei verschiedenen Insektenordnungen unterschiedlich.', 1, '78'),
(37, '2016-04-20 10:12:12', '2016-12-02 22:59:38', 'Tim', 'Werkblei', 'Werkblei ist noch unreines Rohblei, welches sich während des Verhüttungsprozesses im unteren Teil des Ofens ansammelt und bis zu 5 % Verunreinigungen wie Kupfer, Zinn, Antimon, Arsen, Bismut oder Edelmetalle wie Silber und Gold in wechselnden Anteilen enthält. Hierbei wird die silberreiche Legierung Güldischsilber genannt.', 'Das Werkblei verlässt mit ca. 900 bis 1000 °C den Ofen und scheidet bereits beim Abkühlen die Verunreinigungen aus, die bei niedrigeren Temperaturen im Blei schlecht löslich sind. Diese werden als Schlicker abgezogen und entweder in den Ofen zurückgegeben oder separat aufgearbeitet.\r\nDas Werkblei hat je nach Hütte unterschiedliche Zusammensetzung, kommt in der Regel nicht in den Handel, sondern wird weiter raffiniert zu Hüttenblei oder Feinblei.', 0, '99'),
(38, '2016-04-23 21:01:55', '2016-12-09 20:59:08', 'Patrick', 'Parthenophilie', 'Parthenophilie (altgr. παρθένος parthénos „Jungfrau“ und -philie) beschreibt das erotisch-sexuelle Interesse Erwachsener an pubertären Mädchen.', 'Diese Neigung ist aus sexualwissenschaftlicher Sicht von der Pädophilie abzugrenzen, bei der sich das begehrte Objekt im präpubertären Stadium befindet. Der Begriff „Parthenophilie“ wurde lange Zeit nur sehr selten verwendet, gewinnt aber mit der Beschäftigung um den Themenbereich sexueller Missbrauch und der damit einhergehenden genaueren Differenzierung wieder an Bedeutung.\r\nDer Begriff wurde von Magnus Hirschfeld geprägt und erschien erstmals 1906 in dessen Werk Vom Wesen der Liebe. Er wird dort dem Begriff Ephebophilie beigestellt, welcher das erotisch-sexuelle Interesse an pubertierenden Jungen ausdrückt.[1] In seinem Werk Die Homosexualität des Mannes und des Weibes aus dem Jahre 1914 stellt er ein ganzes Begriffssystem vor und beschreibt das Alter vom Beginn bis zum Abschluss der körperlichen Reifung.[2] Beier, Bosinski und Loewit beschreiben unter „Differenzialtypologie dissexuellen Verhaltens“ einen Altersbereich von zirka 12 bis 17 Jahren, wobei sich die weiblichen Kinder und Jugendlichen bereits mindestens in der ersten Phase der körperlichen Sexualentwicklung (beginnende Schambehaarung) befinden. Sie merken ebenfalls an, dass auch ältere junge Frauen attraktiv sein können, sofern sie dem jugendlichen Typus entsprechen, sowie auch Mädchen, die bereits mit elf oder zwölf Jahren in die Pubertät eintreten.[3] Im Gegensatz zur Pädophilie stelle die Parthenophilie „eine sexualbiologisch erwartbare Reaktion“ dar und könne nicht als „Störung der sexuellen Präferenz kategorisiert werden“.', 1, '23'),
(39, '2016-04-25 16:23:36', '2016-10-31 22:59:21', 'Stefan', 'Hahnkampl', 'Das Hahnkampl ist ein 2080 m ü. A. hoher Berg in der Sonnjochgruppe im Karwendel in Tirol.', 'Der Gipfel ist als unschwierige Bergwanderung von der Eng über die Binsalm und den Binssattel zu erreichen (vom Alpengasthof Eng: Aufstiegszeit (über Binssattel): ca. 2:15 Stunden, Abstiegszeit (über Lamsenjoch): ca. 2:00 Stunden, ca. 880 Höhenmeter). Alternativ ist der Gipfel vom Falzthurntal über den Gramaialm-Hochleger (1756 m ü. A.) zu erreichen. Die Gipfelüberschreitung mit dem Abstieg zum Westlichen Lamsenjoch (1940 m ü. A.) erfordert Trittsicherheit und Schwindelfreiheit.', 0, '11'),
(40, '2016-04-29 03:19:35', '2017-10-09 19:59:25', 'Maurice', 'Werft', 'Eine Werft (alt-niederl./friesl.: Der am Wasser baut, siehe auch: Warft) ist ein Betrieb zum Bau und zur Reparatur von Booten und Schiffen.', 'Bis Anfang des 20. Jahrhunderts wurde als die oder das Werft auch ein Flussufer bezeichnet, das für den Handel, Reparatur und Bau von Schiffen eingerichtet war.[1]\r\nMit der einsetzenden Entwicklung großer Luftschiffe und Flugzeuge wurde der Begriff Werft auch auf Anlagen zur Produktion und Grundinstandsetzung im Luftschiffbau (Luftschiffwerft) und Flugzeugbau (Flugzeugwerft) übertragen.\r\nDer klassische Schiffbauplatz einer Werft ist die Helling oder der Helgen. Heutzutage werden Schiffe auf vielen Werften auf überdachten Bauplätzen oder in einer Schiffbauhalle, teilweise in überdachten oder geschützten Baudocks gebaut.\r\nJedes Schiff erhält bei Baubeginn eine Bau-Nr. (Baunummer). Dies ist meist eine fortlaufende Zahl, welche die jeweilige Anzahl der bisher auf der Werft gebauten Schiffe angibt. Es gibt aber auch Werften, die zum Beispiel bei jeweils verschiedenen Bauserien analog auch neue Baunummernblöcke beginnen.\r\nNeben dem Bau werden von Werften ebenso Reparaturen und Umbauten sowie Instandhaltungsmaßnahmen an Schiffen durchgeführt. Auch dabei müssen Schiffe oft in Schwimm- oder Trockendocks trockengelegt werden, sofern bei kleineren Fahrzeugen hierfür nicht Slipanlagen oder Kräne eingesetzt werden.\r\nWerftbetriebe sind zumeist auf bestimmte Arten von Schiffen und Booten ausgerichtet. So wird nach den Typen von Wasserfahrzeugen unterschieden zwischen\r\nBootswerften – für kleinere Fahrzeuge\r\nBinnenschiffswerften – für Binnenschiffe\r\nSeeschiffswerften – für Seeschiffe\r\nDiese sind zum Teil wiederum auf spezielle Schiffstypen spezialisiert. Auch kann der Schwerpunkt der Tätigkeit einer Werft ganz oder teilweise in den Bereichen Bau, Reparatur, Wartung oder Umbau liegen.\r\nDiese Aufgaben werden für Kriegsschiffe zum Teil in Marinearsenalen ausgeführt.\r\nDie Zerlegung von Schiffen erfolgt oft in darauf spezialisierten Abwrackwerften.', 1, '65'),
(41, '2016-05-06 06:38:15', '0000-00-00 00:00:00', 'Patrick', 'DreamSpark', 'Wie wäre es mit einem Softwareverteilungsportal?', 'Maurice: Gute Idee', 0, '5'),
(42, '2016-05-07 18:48:35', '2016-07-09 09:23:45', 'Thomas', 'Hundezwinger', 'Der Hundezwinger ist ein Gegenstand der zu Verteidigungszwecken errichtet wird.Es handelt sich um einen Käfig, der 4 Kampfhunde enthält. Die Hunde greifen automatisch an, wenn sich feindliche Einheiten in der Nähe befinden und kehren danach in den Käfig zurück. In Stronghold Crusader greifen sie nur feindliche Einheiten an. ', 'Stefan: Wir haben einen Hundezwinger im Garten stehen. Wenn wir mal für längere Zeit weg sind über den Tag dann kommt unser Hund da rein. Der Zwinger ist groß und sein Hundehaus passt da auch gut rein. \r\nMissbrauch melden.', 1, '66'),
(43, '2016-05-12 11:27:06', '2016-06-23 12:36:00', 'Stefan', 'Römische Mythologie', 'Personen aus der Römischen Mythologie:', 'Lucifer wird als Vorreiter des Helios gesehen, wobei sein Pferd bisweilen entsprechend der Tageszeit die Farbe wechselt[1] oder er fährt wie dieser im Wagen über den Himmel. ...', 0, '420'),
(44, '2016-05-13 15:48:28', '2016-06-22 13:25:33', 'Stefan', 'Bundeskanzlerin', 'Wie heißt unsere aktuelle Kanzlerin?', 'Angela Merkel wurde am 22. November 2005 zur Bundeskanzlerin gewählt. Die erste Frau und Naturwissenschaftlerin, die das höchste Regierungsamt Deutschlands bekleidet, stützte sich auf eine große Koalition aus CDU/CSU und SPD. Bei Amtsantritt war sie mit 51 Jahren die jüngste Amtsinhaberin, ist die erste ehemalige Bürgerin der DDR als gesamtdeutsche Kanzlerin und nach der Wende Quereinsteigerin aus der Wissenschaft in die Politik.', 1, '2763'),
(45, '2016-05-15 07:56:23', '2016-07-02 21:59:47', 'Tim', 'Innovationsmanagment', 'Die Definition von Innovationsmanagment.', 'Innovationsmanagement ist die systematische Planung, Steuerung und Kontrolle von Innovationen in Organisationen. Im Unterschied zu Kreativität, die sich mit der Entwicklung von Ideen beschäftigt, ist Innovationsmanagement auch auf die Verwertung von Ideen bzw. deren Umsetzung in wirtschaftlich erfolgreiche Produkte bzw. Dienstleistungen ausgerichtet.', 0, '123'),
(46, '2016-05-19 09:23:34', '2016-08-15 19:59:16', 'Patrick', 'Tentorium ', 'Erklärung', 'Das Tentorium ist eine innere Skelettstruktur im Kopf der Insekten, der übrigen Hexapoda (Entognatha) und der Tausendfüßer. Es entsteht aus fingerförmigen Einstülpungen des Exoskeletts, die generell Apodeme genannt werden. Diese sog. Tentoriumsäste können im Kopfinnern frei bleiben oder sich zu einer gemeinsamen Struktur vereinigen. Aufgabe des Tentoriums ist die innere Versteifung der hohlen Kopfkapsel gegen mechanische Beanspruchungen, wie sie z. B. aus der Arbeit der Mundwerkzeuge entstehen können. Außerdem dient die Struktur als Ansatzpunkt und Widerlager für zahlreiche Muskeln. Da das Tentorium aus einer Einstülpung der Kopfkapsel nach innen entsteht, ist seine Ansatzstelle außen meist in Form einer kleinen Einsenkung sichtbar, die Tentoriumsgrube genannt wird. Durch die vier Äste ergeben sich zwei vordere und zwei hintere Tentoriumsgruben. Diese liegen in der Regel innerhalb von Kopfnähten. Ihre Lage ist bei verschiedenen Insektenordnungen unterschiedlich.', 1, '78'),
(47, '2016-05-20 10:12:12', '2016-07-02 21:59:38', 'Tim', 'Werkblei', 'Werkblei ist noch unreines Rohblei, welches sich während des Verhüttungsprozesses im unteren Teil des Ofens ansammelt und bis zu 5 % Verunreinigungen wie Kupfer, Zinn, Antimon, Arsen, Bismut oder Edelmetalle wie Silber und Gold in wechselnden Anteilen enthält. Hierbei wird die silberreiche Legierung Güldischsilber genannt.', 'Das Werkblei verlässt mit ca. 900 bis 1000 °C den Ofen und scheidet bereits beim Abkühlen die Verunreinigungen aus, die bei niedrigeren Temperaturen im Blei schlecht löslich sind. Diese werden als Schlicker abgezogen und entweder in den Ofen zurückgegeben oder separat aufgearbeitet.\r\nDas Werkblei hat je nach Hütte unterschiedliche Zusammensetzung, kommt in der Regel nicht in den Handel, sondern wird weiter raffiniert zu Hüttenblei oder Feinblei.', 0, '99'),
(48, '2016-05-23 21:01:55', '2016-08-09 19:59:08', 'Patrick', 'Parthenophilie', 'Parthenophilie (altgr. παρθένος parthénos „Jungfrau“ und -philie) beschreibt das erotisch-sexuelle Interesse Erwachsener an pubertären Mädchen.', 'Diese Neigung ist aus sexualwissenschaftlicher Sicht von der Pädophilie abzugrenzen, bei der sich das begehrte Objekt im präpubertären Stadium befindet. Der Begriff „Parthenophilie“ wurde lange Zeit nur sehr selten verwendet, gewinnt aber mit der Beschäftigung um den Themenbereich sexueller Missbrauch und der damit einhergehenden genaueren Differenzierung wieder an Bedeutung.\r\nDer Begriff wurde von Magnus Hirschfeld geprägt und erschien erstmals 1906 in dessen Werk Vom Wesen der Liebe. Er wird dort dem Begriff Ephebophilie beigestellt, welcher das erotisch-sexuelle Interesse an pubertierenden Jungen ausdrückt.[1] In seinem Werk Die Homosexualität des Mannes und des Weibes aus dem Jahre 1914 stellt er ein ganzes Begriffssystem vor und beschreibt das Alter vom Beginn bis zum Abschluss der körperlichen Reifung.[2] Beier, Bosinski und Loewit beschreiben unter „Differenzialtypologie dissexuellen Verhaltens“ einen Altersbereich von zirka 12 bis 17 Jahren, wobei sich die weiblichen Kinder und Jugendlichen bereits mindestens in der ersten Phase der körperlichen Sexualentwicklung (beginnende Schambehaarung) befinden. Sie merken ebenfalls an, dass auch ältere junge Frauen attraktiv sein können, sofern sie dem jugendlichen Typus entsprechen, sowie auch Mädchen, die bereits mit elf oder zwölf Jahren in die Pubertät eintreten.[3] Im Gegensatz zur Pädophilie stelle die Parthenophilie „eine sexualbiologisch erwartbare Reaktion“ dar und könne nicht als „Störung der sexuellen Präferenz kategorisiert werden“.', 1, '23'),
(49, '2016-05-25 16:23:36', '2016-10-31 22:59:21', 'Stefan', 'Hahnkampl', 'Das Hahnkampl ist ein 2080 m ü. A. hoher Berg in der Sonnjochgruppe im Karwendel in Tirol.', 'Der Gipfel ist als unschwierige Bergwanderung von der Eng über die Binsalm und den Binssattel zu erreichen (vom Alpengasthof Eng: Aufstiegszeit (über Binssattel): ca. 2:15 Stunden, Abstiegszeit (über Lamsenjoch): ca. 2:00 Stunden, ca. 880 Höhenmeter). Alternativ ist der Gipfel vom Falzthurntal über den Gramaialm-Hochleger (1756 m ü. A.) zu erreichen. Die Gipfelüberschreitung mit dem Abstieg zum Westlichen Lamsenjoch (1940 m ü. A.) erfordert Trittsicherheit und Schwindelfreiheit.', 0, '11'),
(50, '2016-05-29 03:19:35', '2017-08-09 19:59:25', 'Maurice', 'Werft', 'Eine Werft (alt-niederl./friesl.: Der am Wasser baut, siehe auch: Warft) ist ein Betrieb zum Bau und zur Reparatur von Booten und Schiffen.', 'Bis Anfang des 20. Jahrhunderts wurde als die oder das Werft auch ein Flussufer bezeichnet, das für den Handel, Reparatur und Bau von Schiffen eingerichtet war.[1]\r\nMit der einsetzenden Entwicklung großer Luftschiffe und Flugzeuge wurde der Begriff Werft auch auf Anlagen zur Produktion und Grundinstandsetzung im Luftschiffbau (Luftschiffwerft) und Flugzeugbau (Flugzeugwerft) übertragen.\r\nDer klassische Schiffbauplatz einer Werft ist die Helling oder der Helgen. Heutzutage werden Schiffe auf vielen Werften auf überdachten Bauplätzen oder in einer Schiffbauhalle, teilweise in überdachten oder geschützten Baudocks gebaut.\r\nJedes Schiff erhält bei Baubeginn eine Bau-Nr. (Baunummer). Dies ist meist eine fortlaufende Zahl, welche die jeweilige Anzahl der bisher auf der Werft gebauten Schiffe angibt. Es gibt aber auch Werften, die zum Beispiel bei jeweils verschiedenen Bauserien analog auch neue Baunummernblöcke beginnen.\r\nNeben dem Bau werden von Werften ebenso Reparaturen und Umbauten sowie Instandhaltungsmaßnahmen an Schiffen durchgeführt. Auch dabei müssen Schiffe oft in Schwimm- oder Trockendocks trockengelegt werden, sofern bei kleineren Fahrzeugen hierfür nicht Slipanlagen oder Kräne eingesetzt werden.\r\nWerftbetriebe sind zumeist auf bestimmte Arten von Schiffen und Booten ausgerichtet. So wird nach den Typen von Wasserfahrzeugen unterschieden zwischen\r\nBootswerften – für kleinere Fahrzeuge\r\nBinnenschiffswerften – für Binnenschiffe\r\nSeeschiffswerften – für Seeschiffe\r\nDiese sind zum Teil wiederum auf spezielle Schiffstypen spezialisiert. Auch kann der Schwerpunkt der Tätigkeit einer Werft ganz oder teilweise in den Bereichen Bau, Reparatur, Wartung oder Umbau liegen.\r\nDiese Aufgaben werden für Kriegsschiffe zum Teil in Marinearsenalen ausgeführt.\r\nDie Zerlegung von Schiffen erfolgt oft in darauf spezialisierten Abwrackwerften.', 1, '65'),
(51, '2016-06-06 06:38:15', '0000-00-00 00:00:00', 'Patrick', 'DreamSpark', 'Wie wäre es mit einem Softwareverteilungsportal?', 'Maurice: Gute Idee', 0, '5'),
(52, '2016-06-07 18:48:35', '2016-12-09 10:23:45', 'Thomas', 'Hundezwinger', 'Der Hundezwinger ist ein Gegenstand der zu Verteidigungszwecken errichtet wird.Es handelt sich um einen Käfig, der 4 Kampfhunde enthält. Die Hunde greifen automatisch an, wenn sich feindliche Einheiten in der Nähe befinden und kehren danach in den Käfig zurück. In Stronghold Crusader greifen sie nur feindliche Einheiten an. ', 'Stefan: Wir haben einen Hundezwinger im Garten stehen. Wenn wir mal für längere Zeit weg sind über den Tag dann kommt unser Hund da rein. Der Zwinger ist groß und sein Hundehaus passt da auch gut rein. \r\nMissbrauch melden.', 1, '66'),
(53, '2016-06-12 11:27:06', '2016-08-23 12:36:00', 'Stefan', 'Römische Mythologie', 'Personen aus der Römischen Mythologie:', 'Lucifer wird als Vorreiter des Helios gesehen, wobei sein Pferd bisweilen entsprechend der Tageszeit die Farbe wechselt[1] oder er fährt wie dieser im Wagen über den Himmel. ...', 0, '420'),
(54, '2016-06-13 15:48:28', '2016-09-22 13:25:33', 'Stefan', 'Bundeskanzlerin', 'Wie heißt unsere aktuelle Kanzlerin?', 'Angela Merkel wurde am 22. November 2005 zur Bundeskanzlerin gewählt. Die erste Frau und Naturwissenschaftlerin, die das höchste Regierungsamt Deutschlands bekleidet, stützte sich auf eine große Koalition aus CDU/CSU und SPD. Bei Amtsantritt war sie mit 51 Jahren die jüngste Amtsinhaberin, ist die erste ehemalige Bürgerin der DDR als gesamtdeutsche Kanzlerin und nach der Wende Quereinsteigerin aus der Wissenschaft in die Politik.', 1, '2763'),
(55, '2016-06-15 07:56:23', '2016-07-02 21:59:47', 'Tim', 'Innovationsmanagment', 'Die Definition von Innovationsmanagment.', 'Innovationsmanagement ist die systematische Planung, Steuerung und Kontrolle von Innovationen in Organisationen. Im Unterschied zu Kreativität, die sich mit der Entwicklung von Ideen beschäftigt, ist Innovationsmanagement auch auf die Verwertung von Ideen bzw. deren Umsetzung in wirtschaftlich erfolgreiche Produkte bzw. Dienstleistungen ausgerichtet.', 0, '123'),
(56, '2016-06-19 09:23:34', '2016-07-15 19:59:16', 'Patrick', 'Tentorium ', 'Erklärung', 'Das Tentorium ist eine innere Skelettstruktur im Kopf der Insekten, der übrigen Hexapoda (Entognatha) und der Tausendfüßer. Es entsteht aus fingerförmigen Einstülpungen des Exoskeletts, die generell Apodeme genannt werden. Diese sog. Tentoriumsäste können im Kopfinnern frei bleiben oder sich zu einer gemeinsamen Struktur vereinigen. Aufgabe des Tentoriums ist die innere Versteifung der hohlen Kopfkapsel gegen mechanische Beanspruchungen, wie sie z. B. aus der Arbeit der Mundwerkzeuge entstehen können. Außerdem dient die Struktur als Ansatzpunkt und Widerlager für zahlreiche Muskeln. Da das Tentorium aus einer Einstülpung der Kopfkapsel nach innen entsteht, ist seine Ansatzstelle außen meist in Form einer kleinen Einsenkung sichtbar, die Tentoriumsgrube genannt wird. Durch die vier Äste ergeben sich zwei vordere und zwei hintere Tentoriumsgruben. Diese liegen in der Regel innerhalb von Kopfnähten. Ihre Lage ist bei verschiedenen Insektenordnungen unterschiedlich.', 1, '78'),
(57, '2016-06-20 10:12:12', '2016-07-02 21:59:38', 'Tim', 'Werkblei', 'Werkblei ist noch unreines Rohblei, welches sich während des Verhüttungsprozesses im unteren Teil des Ofens ansammelt und bis zu 5 % Verunreinigungen wie Kupfer, Zinn, Antimon, Arsen, Bismut oder Edelmetalle wie Silber und Gold in wechselnden Anteilen enthält. Hierbei wird die silberreiche Legierung Güldischsilber genannt.', 'Das Werkblei verlässt mit ca. 900 bis 1000 °C den Ofen und scheidet bereits beim Abkühlen die Verunreinigungen aus, die bei niedrigeren Temperaturen im Blei schlecht löslich sind. Diese werden als Schlicker abgezogen und entweder in den Ofen zurückgegeben oder separat aufgearbeitet.\r\nDas Werkblei hat je nach Hütte unterschiedliche Zusammensetzung, kommt in der Regel nicht in den Handel, sondern wird weiter raffiniert zu Hüttenblei oder Feinblei.', 0, '99'),
(58, '2016-06-23 21:01:55', '2016-07-09 19:59:08', 'Patrick', 'Parthenophilie', 'Parthenophilie (altgr. παρθένος parthénos „Jungfrau“ und -philie) beschreibt das erotisch-sexuelle Interesse Erwachsener an pubertären Mädchen.', 'Diese Neigung ist aus sexualwissenschaftlicher Sicht von der Pädophilie abzugrenzen, bei der sich das begehrte Objekt im präpubertären Stadium befindet. Der Begriff „Parthenophilie“ wurde lange Zeit nur sehr selten verwendet, gewinnt aber mit der Beschäftigung um den Themenbereich sexueller Missbrauch und der damit einhergehenden genaueren Differenzierung wieder an Bedeutung.\r\nDer Begriff wurde von Magnus Hirschfeld geprägt und erschien erstmals 1906 in dessen Werk Vom Wesen der Liebe. Er wird dort dem Begriff Ephebophilie beigestellt, welcher das erotisch-sexuelle Interesse an pubertierenden Jungen ausdrückt.[1] In seinem Werk Die Homosexualität des Mannes und des Weibes aus dem Jahre 1914 stellt er ein ganzes Begriffssystem vor und beschreibt das Alter vom Beginn bis zum Abschluss der körperlichen Reifung.[2] Beier, Bosinski und Loewit beschreiben unter „Differenzialtypologie dissexuellen Verhaltens“ einen Altersbereich von zirka 12 bis 17 Jahren, wobei sich die weiblichen Kinder und Jugendlichen bereits mindestens in der ersten Phase der körperlichen Sexualentwicklung (beginnende Schambehaarung) befinden. Sie merken ebenfalls an, dass auch ältere junge Frauen attraktiv sein können, sofern sie dem jugendlichen Typus entsprechen, sowie auch Mädchen, die bereits mit elf oder zwölf Jahren in die Pubertät eintreten.[3] Im Gegensatz zur Pädophilie stelle die Parthenophilie „eine sexualbiologisch erwartbare Reaktion“ dar und könne nicht als „Störung der sexuellen Präferenz kategorisiert werden“.', 1, '23'),
(59, '2016-06-25 16:23:36', '2016-07-31 21:59:21', 'Stefan', 'Hahnkampl', 'Das Hahnkampl ist ein 2080 m ü. A. hoher Berg in der Sonnjochgruppe im Karwendel in Tirol.', 'Der Gipfel ist als unschwierige Bergwanderung von der Eng über die Binsalm und den Binssattel zu erreichen (vom Alpengasthof Eng: Aufstiegszeit (über Binssattel): ca. 2:15 Stunden, Abstiegszeit (über Lamsenjoch): ca. 2:00 Stunden, ca. 880 Höhenmeter). Alternativ ist der Gipfel vom Falzthurntal über den Gramaialm-Hochleger (1756 m ü. A.) zu erreichen. Die Gipfelüberschreitung mit dem Abstieg zum Westlichen Lamsenjoch (1940 m ü. A.) erfordert Trittsicherheit und Schwindelfreiheit.', 0, '11');
INSERT INTO `idea` (`ID`, `created`, `updated`, `author`, `title`, `description`, `comment`, `accepted`, `version`) VALUES
(60, '2016-06-29 03:19:35', '2017-07-09 19:59:25', 'Maurice', 'Werft', 'Eine Werft (alt-niederl./friesl.: Der am Wasser baut, siehe auch: Warft) ist ein Betrieb zum Bau und zur Reparatur von Booten und Schiffen.', 'Bis Anfang des 20. Jahrhunderts wurde als die oder das Werft auch ein Flussufer bezeichnet, das für den Handel, Reparatur und Bau von Schiffen eingerichtet war.[1]\r\nMit der einsetzenden Entwicklung großer Luftschiffe und Flugzeuge wurde der Begriff Werft auch auf Anlagen zur Produktion und Grundinstandsetzung im Luftschiffbau (Luftschiffwerft) und Flugzeugbau (Flugzeugwerft) übertragen.\r\nDer klassische Schiffbauplatz einer Werft ist die Helling oder der Helgen. Heutzutage werden Schiffe auf vielen Werften auf überdachten Bauplätzen oder in einer Schiffbauhalle, teilweise in überdachten oder geschützten Baudocks gebaut.\r\nJedes Schiff erhält bei Baubeginn eine Bau-Nr. (Baunummer). Dies ist meist eine fortlaufende Zahl, welche die jeweilige Anzahl der bisher auf der Werft gebauten Schiffe angibt. Es gibt aber auch Werften, die zum Beispiel bei jeweils verschiedenen Bauserien analog auch neue Baunummernblöcke beginnen.\r\nNeben dem Bau werden von Werften ebenso Reparaturen und Umbauten sowie Instandhaltungsmaßnahmen an Schiffen durchgeführt. Auch dabei müssen Schiffe oft in Schwimm- oder Trockendocks trockengelegt werden, sofern bei kleineren Fahrzeugen hierfür nicht Slipanlagen oder Kräne eingesetzt werden.\r\nWerftbetriebe sind zumeist auf bestimmte Arten von Schiffen und Booten ausgerichtet. So wird nach den Typen von Wasserfahrzeugen unterschieden zwischen\r\nBootswerften – für kleinere Fahrzeuge\r\nBinnenschiffswerften – für Binnenschiffe\r\nSeeschiffswerften – für Seeschiffe\r\nDiese sind zum Teil wiederum auf spezielle Schiffstypen spezialisiert. Auch kann der Schwerpunkt der Tätigkeit einer Werft ganz oder teilweise in den Bereichen Bau, Reparatur, Wartung oder Umbau liegen.\r\nDiese Aufgaben werden für Kriegsschiffe zum Teil in Marinearsenalen ausgeführt.\r\nDie Zerlegung von Schiffen erfolgt oft in darauf spezialisierten Abwrackwerften.', 1, '65'),
(61, '2016-07-06 06:38:15', '0000-00-00 00:00:00', 'Patrick', 'DreamSpark', 'Wie wäre es mit einem Softwareverteilungsportal?', 'Maurice: Gute Idee', 0, '5'),
(62, '2016-07-07 18:48:35', '2016-09-09 09:23:45', 'Thomas', 'Hundezwinger', 'Der Hundezwinger ist ein Gegenstand der zu Verteidigungszwecken errichtet wird.Es handelt sich um einen Käfig, der 4 Kampfhunde enthält. Die Hunde greifen automatisch an, wenn sich feindliche Einheiten in der Nähe befinden und kehren danach in den Käfig zurück. In Stronghold Crusader greifen sie nur feindliche Einheiten an. ', 'Stefan: Wir haben einen Hundezwinger im Garten stehen. Wenn wir mal für längere Zeit weg sind über den Tag dann kommt unser Hund da rein. Der Zwinger ist groß und sein Hundehaus passt da auch gut rein. \r\nMissbrauch melden.', 1, '66'),
(63, '2016-07-12 11:27:06', '2016-09-23 12:36:00', 'Stefan', 'Römische Mythologie', 'Personen aus der Römischen Mythologie:', 'Lucifer wird als Vorreiter des Helios gesehen, wobei sein Pferd bisweilen entsprechend der Tageszeit die Farbe wechselt[1] oder er fährt wie dieser im Wagen über den Himmel. ...', 0, '420'),
(64, '2016-07-13 15:48:28', '2016-11-22 14:25:33', 'Stefan', 'Bundeskanzlerin', 'Wie heißt unsere aktuelle Kanzlerin?', 'Angela Merkel wurde am 22. November 2005 zur Bundeskanzlerin gewählt. Die erste Frau und Naturwissenschaftlerin, die das höchste Regierungsamt Deutschlands bekleidet, stützte sich auf eine große Koalition aus CDU/CSU und SPD. Bei Amtsantritt war sie mit 51 Jahren die jüngste Amtsinhaberin, ist die erste ehemalige Bürgerin der DDR als gesamtdeutsche Kanzlerin und nach der Wende Quereinsteigerin aus der Wissenschaft in die Politik.', 1, '2763'),
(65, '2016-07-15 07:56:23', '2016-09-02 21:59:47', 'Tim', 'Innovationsmanagment', 'Die Definition von Innovationsmanagment.', 'Innovationsmanagement ist die systematische Planung, Steuerung und Kontrolle von Innovationen in Organisationen. Im Unterschied zu Kreativität, die sich mit der Entwicklung von Ideen beschäftigt, ist Innovationsmanagement auch auf die Verwertung von Ideen bzw. deren Umsetzung in wirtschaftlich erfolgreiche Produkte bzw. Dienstleistungen ausgerichtet.', 0, '123'),
(66, '2016-07-19 09:23:34', '2016-09-15 19:59:16', 'Patrick', 'Tentorium ', 'Erklärung', 'Das Tentorium ist eine innere Skelettstruktur im Kopf der Insekten, der übrigen Hexapoda (Entognatha) und der Tausendfüßer. Es entsteht aus fingerförmigen Einstülpungen des Exoskeletts, die generell Apodeme genannt werden. Diese sog. Tentoriumsäste können im Kopfinnern frei bleiben oder sich zu einer gemeinsamen Struktur vereinigen. Aufgabe des Tentoriums ist die innere Versteifung der hohlen Kopfkapsel gegen mechanische Beanspruchungen, wie sie z. B. aus der Arbeit der Mundwerkzeuge entstehen können. Außerdem dient die Struktur als Ansatzpunkt und Widerlager für zahlreiche Muskeln. Da das Tentorium aus einer Einstülpung der Kopfkapsel nach innen entsteht, ist seine Ansatzstelle außen meist in Form einer kleinen Einsenkung sichtbar, die Tentoriumsgrube genannt wird. Durch die vier Äste ergeben sich zwei vordere und zwei hintere Tentoriumsgruben. Diese liegen in der Regel innerhalb von Kopfnähten. Ihre Lage ist bei verschiedenen Insektenordnungen unterschiedlich.', 1, '78'),
(67, '2016-07-20 10:12:12', '2016-09-02 21:59:38', 'Tim', 'Werkblei', 'Werkblei ist noch unreines Rohblei, welches sich während des Verhüttungsprozesses im unteren Teil des Ofens ansammelt und bis zu 5 % Verunreinigungen wie Kupfer, Zinn, Antimon, Arsen, Bismut oder Edelmetalle wie Silber und Gold in wechselnden Anteilen enthält. Hierbei wird die silberreiche Legierung Güldischsilber genannt.', 'Das Werkblei verlässt mit ca. 900 bis 1000 °C den Ofen und scheidet bereits beim Abkühlen die Verunreinigungen aus, die bei niedrigeren Temperaturen im Blei schlecht löslich sind. Diese werden als Schlicker abgezogen und entweder in den Ofen zurückgegeben oder separat aufgearbeitet.\r\nDas Werkblei hat je nach Hütte unterschiedliche Zusammensetzung, kommt in der Regel nicht in den Handel, sondern wird weiter raffiniert zu Hüttenblei oder Feinblei.', 0, '99'),
(68, '2016-07-23 21:01:55', '2016-09-09 19:59:08', 'Patrick', 'Parthenophilie', 'Parthenophilie (altgr. παρθένος parthénos „Jungfrau“ und -philie) beschreibt das erotisch-sexuelle Interesse Erwachsener an pubertären Mädchen.', 'Diese Neigung ist aus sexualwissenschaftlicher Sicht von der Pädophilie abzugrenzen, bei der sich das begehrte Objekt im präpubertären Stadium befindet. Der Begriff „Parthenophilie“ wurde lange Zeit nur sehr selten verwendet, gewinnt aber mit der Beschäftigung um den Themenbereich sexueller Missbrauch und der damit einhergehenden genaueren Differenzierung wieder an Bedeutung.\r\nDer Begriff wurde von Magnus Hirschfeld geprägt und erschien erstmals 1906 in dessen Werk Vom Wesen der Liebe. Er wird dort dem Begriff Ephebophilie beigestellt, welcher das erotisch-sexuelle Interesse an pubertierenden Jungen ausdrückt.[1] In seinem Werk Die Homosexualität des Mannes und des Weibes aus dem Jahre 1914 stellt er ein ganzes Begriffssystem vor und beschreibt das Alter vom Beginn bis zum Abschluss der körperlichen Reifung.[2] Beier, Bosinski und Loewit beschreiben unter „Differenzialtypologie dissexuellen Verhaltens“ einen Altersbereich von zirka 12 bis 17 Jahren, wobei sich die weiblichen Kinder und Jugendlichen bereits mindestens in der ersten Phase der körperlichen Sexualentwicklung (beginnende Schambehaarung) befinden. Sie merken ebenfalls an, dass auch ältere junge Frauen attraktiv sein können, sofern sie dem jugendlichen Typus entsprechen, sowie auch Mädchen, die bereits mit elf oder zwölf Jahren in die Pubertät eintreten.[3] Im Gegensatz zur Pädophilie stelle die Parthenophilie „eine sexualbiologisch erwartbare Reaktion“ dar und könne nicht als „Störung der sexuellen Präferenz kategorisiert werden“.', 1, '23'),
(69, '2016-07-25 16:23:36', '0000-00-00 00:00:00', 'Stefan', 'Hahnkampl', 'Das Hahnkampl ist ein 2080 m ü. A. hoher Berg in der Sonnjochgruppe im Karwendel in Tirol.', 'Der Gipfel ist als unschwierige Bergwanderung von der Eng über die Binsalm und den Binssattel zu erreichen (vom Alpengasthof Eng: Aufstiegszeit (über Binssattel): ca. 2:15 Stunden, Abstiegszeit (über Lamsenjoch): ca. 2:00 Stunden, ca. 880 Höhenmeter). Alternativ ist der Gipfel vom Falzthurntal über den Gramaialm-Hochleger (1756 m ü. A.) zu erreichen. Die Gipfelüberschreitung mit dem Abstieg zum Westlichen Lamsenjoch (1940 m ü. A.) erfordert Trittsicherheit und Schwindelfreiheit.', 0, '11'),
(70, '2016-07-29 03:19:35', '2017-09-09 19:59:25', 'Maurice', 'Werft', 'Eine Werft (alt-niederl./friesl.: Der am Wasser baut, siehe auch: Warft) ist ein Betrieb zum Bau und zur Reparatur von Booten und Schiffen.', 'Bis Anfang des 20. Jahrhunderts wurde als die oder das Werft auch ein Flussufer bezeichnet, das für den Handel, Reparatur und Bau von Schiffen eingerichtet war.[1]\r\nMit der einsetzenden Entwicklung großer Luftschiffe und Flugzeuge wurde der Begriff Werft auch auf Anlagen zur Produktion und Grundinstandsetzung im Luftschiffbau (Luftschiffwerft) und Flugzeugbau (Flugzeugwerft) übertragen.\r\nDer klassische Schiffbauplatz einer Werft ist die Helling oder der Helgen. Heutzutage werden Schiffe auf vielen Werften auf überdachten Bauplätzen oder in einer Schiffbauhalle, teilweise in überdachten oder geschützten Baudocks gebaut.\r\nJedes Schiff erhält bei Baubeginn eine Bau-Nr. (Baunummer). Dies ist meist eine fortlaufende Zahl, welche die jeweilige Anzahl der bisher auf der Werft gebauten Schiffe angibt. Es gibt aber auch Werften, die zum Beispiel bei jeweils verschiedenen Bauserien analog auch neue Baunummernblöcke beginnen.\r\nNeben dem Bau werden von Werften ebenso Reparaturen und Umbauten sowie Instandhaltungsmaßnahmen an Schiffen durchgeführt. Auch dabei müssen Schiffe oft in Schwimm- oder Trockendocks trockengelegt werden, sofern bei kleineren Fahrzeugen hierfür nicht Slipanlagen oder Kräne eingesetzt werden.\r\nWerftbetriebe sind zumeist auf bestimmte Arten von Schiffen und Booten ausgerichtet. So wird nach den Typen von Wasserfahrzeugen unterschieden zwischen\r\nBootswerften – für kleinere Fahrzeuge\r\nBinnenschiffswerften – für Binnenschiffe\r\nSeeschiffswerften – für Seeschiffe\r\nDiese sind zum Teil wiederum auf spezielle Schiffstypen spezialisiert. Auch kann der Schwerpunkt der Tätigkeit einer Werft ganz oder teilweise in den Bereichen Bau, Reparatur, Wartung oder Umbau liegen.\r\nDiese Aufgaben werden für Kriegsschiffe zum Teil in Marinearsenalen ausgeführt.\r\nDie Zerlegung von Schiffen erfolgt oft in darauf spezialisierten Abwrackwerften.', 1, '65'),
(71, '2016-08-06 06:38:15', '2016-10-31 22:59:33', 'Patrick', 'DreamSpark', 'Wie wäre es mit einem Softwareverteilungsportal?', 'Maurice: Gute Idee', 0, '5'),
(72, '2016-08-07 18:48:35', '2016-10-09 09:23:45', 'Thomas', 'Hundezwinger', 'Der Hundezwinger ist ein Gegenstand der zu Verteidigungszwecken errichtet wird.Es handelt sich um einen Käfig, der 4 Kampfhunde enthält. Die Hunde greifen automatisch an, wenn sich feindliche Einheiten in der Nähe befinden und kehren danach in den Käfig zurück. In Stronghold Crusader greifen sie nur feindliche Einheiten an. ', 'Stefan: Wir haben einen Hundezwinger im Garten stehen. Wenn wir mal für längere Zeit weg sind über den Tag dann kommt unser Hund da rein. Der Zwinger ist groß und sein Hundehaus passt da auch gut rein. \r\nMissbrauch melden.', 1, '66'),
(73, '2016-08-12 11:27:06', '2016-10-23 12:36:00', 'Stefan', 'Römische Mythologie', 'Personen aus der Römischen Mythologie:', 'Lucifer wird als Vorreiter des Helios gesehen, wobei sein Pferd bisweilen entsprechend der Tageszeit die Farbe wechselt[1] oder er fährt wie dieser im Wagen über den Himmel. ...', 0, '420'),
(74, '2016-08-13 15:48:28', '2016-09-22 13:25:33', 'Stefan', 'Bundeskanzlerin', 'Wie heißt unsere aktuelle Kanzlerin?', 'Angela Merkel wurde am 22. November 2005 zur Bundeskanzlerin gewählt. Die erste Frau und Naturwissenschaftlerin, die das höchste Regierungsamt Deutschlands bekleidet, stützte sich auf eine große Koalition aus CDU/CSU und SPD. Bei Amtsantritt war sie mit 51 Jahren die jüngste Amtsinhaberin, ist die erste ehemalige Bürgerin der DDR als gesamtdeutsche Kanzlerin und nach der Wende Quereinsteigerin aus der Wissenschaft in die Politik.', 1, '2763'),
(75, '2016-08-15 07:56:23', '2016-10-02 21:59:47', 'Tim', 'Innovationsmanagment', 'Die Definition von Innovationsmanagment.', 'Innovationsmanagement ist die systematische Planung, Steuerung und Kontrolle von Innovationen in Organisationen. Im Unterschied zu Kreativität, die sich mit der Entwicklung von Ideen beschäftigt, ist Innovationsmanagement auch auf die Verwertung von Ideen bzw. deren Umsetzung in wirtschaftlich erfolgreiche Produkte bzw. Dienstleistungen ausgerichtet.', 0, '123'),
(76, '2016-08-19 09:23:34', '2016-10-15 19:59:16', 'Patrick', 'Tentorium ', 'Erklärung', 'Das Tentorium ist eine innere Skelettstruktur im Kopf der Insekten, der übrigen Hexapoda (Entognatha) und der Tausendfüßer. Es entsteht aus fingerförmigen Einstülpungen des Exoskeletts, die generell Apodeme genannt werden. Diese sog. Tentoriumsäste können im Kopfinnern frei bleiben oder sich zu einer gemeinsamen Struktur vereinigen. Aufgabe des Tentoriums ist die innere Versteifung der hohlen Kopfkapsel gegen mechanische Beanspruchungen, wie sie z. B. aus der Arbeit der Mundwerkzeuge entstehen können. Außerdem dient die Struktur als Ansatzpunkt und Widerlager für zahlreiche Muskeln. Da das Tentorium aus einer Einstülpung der Kopfkapsel nach innen entsteht, ist seine Ansatzstelle außen meist in Form einer kleinen Einsenkung sichtbar, die Tentoriumsgrube genannt wird. Durch die vier Äste ergeben sich zwei vordere und zwei hintere Tentoriumsgruben. Diese liegen in der Regel innerhalb von Kopfnähten. Ihre Lage ist bei verschiedenen Insektenordnungen unterschiedlich.', 1, '78'),
(77, '2016-08-20 10:12:12', '2016-10-02 21:59:38', 'Tim', 'Werkblei', 'Werkblei ist noch unreines Rohblei, welches sich während des Verhüttungsprozesses im unteren Teil des Ofens ansammelt und bis zu 5 % Verunreinigungen wie Kupfer, Zinn, Antimon, Arsen, Bismut oder Edelmetalle wie Silber und Gold in wechselnden Anteilen enthält. Hierbei wird die silberreiche Legierung Güldischsilber genannt.', 'Das Werkblei verlässt mit ca. 900 bis 1000 °C den Ofen und scheidet bereits beim Abkühlen die Verunreinigungen aus, die bei niedrigeren Temperaturen im Blei schlecht löslich sind. Diese werden als Schlicker abgezogen und entweder in den Ofen zurückgegeben oder separat aufgearbeitet.\r\nDas Werkblei hat je nach Hütte unterschiedliche Zusammensetzung, kommt in der Regel nicht in den Handel, sondern wird weiter raffiniert zu Hüttenblei oder Feinblei.', 0, '99'),
(78, '2016-08-23 21:01:55', '2016-10-09 19:59:08', 'Patrick', 'Parthenophilie', 'Parthenophilie (altgr. παρθένος parthénos „Jungfrau“ und -philie) beschreibt das erotisch-sexuelle Interesse Erwachsener an pubertären Mädchen.', 'Diese Neigung ist aus sexualwissenschaftlicher Sicht von der Pädophilie abzugrenzen, bei der sich das begehrte Objekt im präpubertären Stadium befindet. Der Begriff „Parthenophilie“ wurde lange Zeit nur sehr selten verwendet, gewinnt aber mit der Beschäftigung um den Themenbereich sexueller Missbrauch und der damit einhergehenden genaueren Differenzierung wieder an Bedeutung.\r\nDer Begriff wurde von Magnus Hirschfeld geprägt und erschien erstmals 1906 in dessen Werk Vom Wesen der Liebe. Er wird dort dem Begriff Ephebophilie beigestellt, welcher das erotisch-sexuelle Interesse an pubertierenden Jungen ausdrückt.[1] In seinem Werk Die Homosexualität des Mannes und des Weibes aus dem Jahre 1914 stellt er ein ganzes Begriffssystem vor und beschreibt das Alter vom Beginn bis zum Abschluss der körperlichen Reifung.[2] Beier, Bosinski und Loewit beschreiben unter „Differenzialtypologie dissexuellen Verhaltens“ einen Altersbereich von zirka 12 bis 17 Jahren, wobei sich die weiblichen Kinder und Jugendlichen bereits mindestens in der ersten Phase der körperlichen Sexualentwicklung (beginnende Schambehaarung) befinden. Sie merken ebenfalls an, dass auch ältere junge Frauen attraktiv sein können, sofern sie dem jugendlichen Typus entsprechen, sowie auch Mädchen, die bereits mit elf oder zwölf Jahren in die Pubertät eintreten.[3] Im Gegensatz zur Pädophilie stelle die Parthenophilie „eine sexualbiologisch erwartbare Reaktion“ dar und könne nicht als „Störung der sexuellen Präferenz kategorisiert werden“.', 1, '23'),
(79, '2016-08-25 16:23:36', '2016-10-31 22:59:21', 'Stefan', 'Hahnkampl', 'Das Hahnkampl ist ein 2080 m ü. A. hoher Berg in der Sonnjochgruppe im Karwendel in Tirol.', 'Der Gipfel ist als unschwierige Bergwanderung von der Eng über die Binsalm und den Binssattel zu erreichen (vom Alpengasthof Eng: Aufstiegszeit (über Binssattel): ca. 2:15 Stunden, Abstiegszeit (über Lamsenjoch): ca. 2:00 Stunden, ca. 880 Höhenmeter). Alternativ ist der Gipfel vom Falzthurntal über den Gramaialm-Hochleger (1756 m ü. A.) zu erreichen. Die Gipfelüberschreitung mit dem Abstieg zum Westlichen Lamsenjoch (1940 m ü. A.) erfordert Trittsicherheit und Schwindelfreiheit.', 0, '11'),
(80, '2016-08-29 03:19:35', '2017-10-09 19:59:25', 'Maurice', 'Werft', 'Eine Werft (alt-niederl./friesl.: Der am Wasser baut, siehe auch: Warft) ist ein Betrieb zum Bau und zur Reparatur von Booten und Schiffen.', 'Bis Anfang des 20. Jahrhunderts wurde als die oder das Werft auch ein Flussufer bezeichnet, das für den Handel, Reparatur und Bau von Schiffen eingerichtet war.[1]\r\nMit der einsetzenden Entwicklung großer Luftschiffe und Flugzeuge wurde der Begriff Werft auch auf Anlagen zur Produktion und Grundinstandsetzung im Luftschiffbau (Luftschiffwerft) und Flugzeugbau (Flugzeugwerft) übertragen.\r\nDer klassische Schiffbauplatz einer Werft ist die Helling oder der Helgen. Heutzutage werden Schiffe auf vielen Werften auf überdachten Bauplätzen oder in einer Schiffbauhalle, teilweise in überdachten oder geschützten Baudocks gebaut.\r\nJedes Schiff erhält bei Baubeginn eine Bau-Nr. (Baunummer). Dies ist meist eine fortlaufende Zahl, welche die jeweilige Anzahl der bisher auf der Werft gebauten Schiffe angibt. Es gibt aber auch Werften, die zum Beispiel bei jeweils verschiedenen Bauserien analog auch neue Baunummernblöcke beginnen.\r\nNeben dem Bau werden von Werften ebenso Reparaturen und Umbauten sowie Instandhaltungsmaßnahmen an Schiffen durchgeführt. Auch dabei müssen Schiffe oft in Schwimm- oder Trockendocks trockengelegt werden, sofern bei kleineren Fahrzeugen hierfür nicht Slipanlagen oder Kräne eingesetzt werden.\r\nWerftbetriebe sind zumeist auf bestimmte Arten von Schiffen und Booten ausgerichtet. So wird nach den Typen von Wasserfahrzeugen unterschieden zwischen\r\nBootswerften – für kleinere Fahrzeuge\r\nBinnenschiffswerften – für Binnenschiffe\r\nSeeschiffswerften – für Seeschiffe\r\nDiese sind zum Teil wiederum auf spezielle Schiffstypen spezialisiert. Auch kann der Schwerpunkt der Tätigkeit einer Werft ganz oder teilweise in den Bereichen Bau, Reparatur, Wartung oder Umbau liegen.\r\nDiese Aufgaben werden für Kriegsschiffe zum Teil in Marinearsenalen ausgeführt.\r\nDie Zerlegung von Schiffen erfolgt oft in darauf spezialisierten Abwrackwerften.', 1, '65'),
(81, '2016-09-06 06:38:15', '0000-00-00 00:00:00', 'Patrick', 'DreamSpark', 'Wie wäre es mit einem Softwareverteilungsportal?', 'Maurice: Gute Idee', 0, '5'),
(82, '2016-09-07 18:48:35', '2016-11-09 10:23:45', 'Thomas', 'Hundezwinger', 'Der Hundezwinger ist ein Gegenstand der zu Verteidigungszwecken errichtet wird.Es handelt sich um einen Käfig, der 4 Kampfhunde enthält. Die Hunde greifen automatisch an, wenn sich feindliche Einheiten in der Nähe befinden und kehren danach in den Käfig zurück. In Stronghold Crusader greifen sie nur feindliche Einheiten an. ', 'Stefan: Wir haben einen Hundezwinger im Garten stehen. Wenn wir mal für längere Zeit weg sind über den Tag dann kommt unser Hund da rein. Der Zwinger ist groß und sein Hundehaus passt da auch gut rein. \r\nMissbrauch melden.', 1, '66'),
(83, '2016-09-12 11:27:06', '2016-11-23 13:36:00', 'Stefan', 'Römische Mythologie', 'Personen aus der Römischen Mythologie:', 'Lucifer wird als Vorreiter des Helios gesehen, wobei sein Pferd bisweilen entsprechend der Tageszeit die Farbe wechselt[1] oder er fährt wie dieser im Wagen über den Himmel. ...', 0, '420'),
(84, '2016-09-13 15:48:28', '2016-11-22 14:25:33', 'Stefan', 'Bundeskanzlerin', 'Wie heißt unsere aktuelle Kanzlerin?', 'Angela Merkel wurde am 22. November 2005 zur Bundeskanzlerin gewählt. Die erste Frau und Naturwissenschaftlerin, die das höchste Regierungsamt Deutschlands bekleidet, stützte sich auf eine große Koalition aus CDU/CSU und SPD. Bei Amtsantritt war sie mit 51 Jahren die jüngste Amtsinhaberin, ist die erste ehemalige Bürgerin der DDR als gesamtdeutsche Kanzlerin und nach der Wende Quereinsteigerin aus der Wissenschaft in die Politik.', 1, '2763'),
(85, '2016-09-15 07:56:23', '2016-11-02 22:59:47', 'Tim', 'Innovationsmanagment', 'Die Definition von Innovationsmanagment.', 'Innovationsmanagement ist die systematische Planung, Steuerung und Kontrolle von Innovationen in Organisationen. Im Unterschied zu Kreativität, die sich mit der Entwicklung von Ideen beschäftigt, ist Innovationsmanagement auch auf die Verwertung von Ideen bzw. deren Umsetzung in wirtschaftlich erfolgreiche Produkte bzw. Dienstleistungen ausgerichtet.', 0, '123'),
(86, '2016-09-19 09:23:34', '2016-11-15 20:59:16', 'Patrick', 'Tentorium ', 'Erklärung', 'Das Tentorium ist eine innere Skelettstruktur im Kopf der Insekten, der übrigen Hexapoda (Entognatha) und der Tausendfüßer. Es entsteht aus fingerförmigen Einstülpungen des Exoskeletts, die generell Apodeme genannt werden. Diese sog. Tentoriumsäste können im Kopfinnern frei bleiben oder sich zu einer gemeinsamen Struktur vereinigen. Aufgabe des Tentoriums ist die innere Versteifung der hohlen Kopfkapsel gegen mechanische Beanspruchungen, wie sie z. B. aus der Arbeit der Mundwerkzeuge entstehen können. Außerdem dient die Struktur als Ansatzpunkt und Widerlager für zahlreiche Muskeln. Da das Tentorium aus einer Einstülpung der Kopfkapsel nach innen entsteht, ist seine Ansatzstelle außen meist in Form einer kleinen Einsenkung sichtbar, die Tentoriumsgrube genannt wird. Durch die vier Äste ergeben sich zwei vordere und zwei hintere Tentoriumsgruben. Diese liegen in der Regel innerhalb von Kopfnähten. Ihre Lage ist bei verschiedenen Insektenordnungen unterschiedlich.', 1, '78'),
(87, '2016-09-20 10:12:12', '2016-11-02 22:59:38', 'Tim', 'Werkblei', 'Werkblei ist noch unreines Rohblei, welches sich während des Verhüttungsprozesses im unteren Teil des Ofens ansammelt und bis zu 5 % Verunreinigungen wie Kupfer, Zinn, Antimon, Arsen, Bismut oder Edelmetalle wie Silber und Gold in wechselnden Anteilen enthält. Hierbei wird die silberreiche Legierung Güldischsilber genannt.', 'Das Werkblei verlässt mit ca. 900 bis 1000 °C den Ofen und scheidet bereits beim Abkühlen die Verunreinigungen aus, die bei niedrigeren Temperaturen im Blei schlecht löslich sind. Diese werden als Schlicker abgezogen und entweder in den Ofen zurückgegeben oder separat aufgearbeitet.\r\nDas Werkblei hat je nach Hütte unterschiedliche Zusammensetzung, kommt in der Regel nicht in den Handel, sondern wird weiter raffiniert zu Hüttenblei oder Feinblei.', 0, '99'),
(88, '2016-09-23 21:01:55', '2016-11-09 20:59:08', 'Patrick', 'Parthenophilie', 'Parthenophilie (altgr. παρθένος parthénos „Jungfrau“ und -philie) beschreibt das erotisch-sexuelle Interesse Erwachsener an pubertären Mädchen.', 'Diese Neigung ist aus sexualwissenschaftlicher Sicht von der Pädophilie abzugrenzen, bei der sich das begehrte Objekt im präpubertären Stadium befindet. Der Begriff „Parthenophilie“ wurde lange Zeit nur sehr selten verwendet, gewinnt aber mit der Beschäftigung um den Themenbereich sexueller Missbrauch und der damit einhergehenden genaueren Differenzierung wieder an Bedeutung.\r\nDer Begriff wurde von Magnus Hirschfeld geprägt und erschien erstmals 1906 in dessen Werk Vom Wesen der Liebe. Er wird dort dem Begriff Ephebophilie beigestellt, welcher das erotisch-sexuelle Interesse an pubertierenden Jungen ausdrückt.[1] In seinem Werk Die Homosexualität des Mannes und des Weibes aus dem Jahre 1914 stellt er ein ganzes Begriffssystem vor und beschreibt das Alter vom Beginn bis zum Abschluss der körperlichen Reifung.[2] Beier, Bosinski und Loewit beschreiben unter „Differenzialtypologie dissexuellen Verhaltens“ einen Altersbereich von zirka 12 bis 17 Jahren, wobei sich die weiblichen Kinder und Jugendlichen bereits mindestens in der ersten Phase der körperlichen Sexualentwicklung (beginnende Schambehaarung) befinden. Sie merken ebenfalls an, dass auch ältere junge Frauen attraktiv sein können, sofern sie dem jugendlichen Typus entsprechen, sowie auch Mädchen, die bereits mit elf oder zwölf Jahren in die Pubertät eintreten.[3] Im Gegensatz zur Pädophilie stelle die Parthenophilie „eine sexualbiologisch erwartbare Reaktion“ dar und könne nicht als „Störung der sexuellen Präferenz kategorisiert werden“.', 1, '23'),
(89, '2016-09-25 16:23:36', '0000-00-00 00:00:00', 'Stefan', 'Hahnkampl', 'Das Hahnkampl ist ein 2080 m ü. A. hoher Berg in der Sonnjochgruppe im Karwendel in Tirol.', 'Der Gipfel ist als unschwierige Bergwanderung von der Eng über die Binsalm und den Binssattel zu erreichen (vom Alpengasthof Eng: Aufstiegszeit (über Binssattel): ca. 2:15 Stunden, Abstiegszeit (über Lamsenjoch): ca. 2:00 Stunden, ca. 880 Höhenmeter). Alternativ ist der Gipfel vom Falzthurntal über den Gramaialm-Hochleger (1756 m ü. A.) zu erreichen. Die Gipfelüberschreitung mit dem Abstieg zum Westlichen Lamsenjoch (1940 m ü. A.) erfordert Trittsicherheit und Schwindelfreiheit.', 0, '11'),
(90, '2016-09-29 03:19:35', '2017-11-09 20:59:25', 'Maurice', 'Werft', 'Eine Werft (alt-niederl./friesl.: Der am Wasser baut, siehe auch: Warft) ist ein Betrieb zum Bau und zur Reparatur von Booten und Schiffen.', 'Bis Anfang des 20. Jahrhunderts wurde als die oder das Werft auch ein Flussufer bezeichnet, das für den Handel, Reparatur und Bau von Schiffen eingerichtet war.[1]\r\nMit der einsetzenden Entwicklung großer Luftschiffe und Flugzeuge wurde der Begriff Werft auch auf Anlagen zur Produktion und Grundinstandsetzung im Luftschiffbau (Luftschiffwerft) und Flugzeugbau (Flugzeugwerft) übertragen.\r\nDer klassische Schiffbauplatz einer Werft ist die Helling oder der Helgen. Heutzutage werden Schiffe auf vielen Werften auf überdachten Bauplätzen oder in einer Schiffbauhalle, teilweise in überdachten oder geschützten Baudocks gebaut.\r\nJedes Schiff erhält bei Baubeginn eine Bau-Nr. (Baunummer). Dies ist meist eine fortlaufende Zahl, welche die jeweilige Anzahl der bisher auf der Werft gebauten Schiffe angibt. Es gibt aber auch Werften, die zum Beispiel bei jeweils verschiedenen Bauserien analog auch neue Baunummernblöcke beginnen.\r\nNeben dem Bau werden von Werften ebenso Reparaturen und Umbauten sowie Instandhaltungsmaßnahmen an Schiffen durchgeführt. Auch dabei müssen Schiffe oft in Schwimm- oder Trockendocks trockengelegt werden, sofern bei kleineren Fahrzeugen hierfür nicht Slipanlagen oder Kräne eingesetzt werden.\r\nWerftbetriebe sind zumeist auf bestimmte Arten von Schiffen und Booten ausgerichtet. So wird nach den Typen von Wasserfahrzeugen unterschieden zwischen\r\nBootswerften – für kleinere Fahrzeuge\r\nBinnenschiffswerften – für Binnenschiffe\r\nSeeschiffswerften – für Seeschiffe\r\nDiese sind zum Teil wiederum auf spezielle Schiffstypen spezialisiert. Auch kann der Schwerpunkt der Tätigkeit einer Werft ganz oder teilweise in den Bereichen Bau, Reparatur, Wartung oder Umbau liegen.\r\nDiese Aufgaben werden für Kriegsschiffe zum Teil in Marinearsenalen ausgeführt.\r\nDie Zerlegung von Schiffen erfolgt oft in darauf spezialisierten Abwrackwerften.', 1, '65'),
(91, '2016-11-06 07:38:15', '2016-12-31 22:59:33', 'Maurice', 'Frohes Neues', 'Ich wünsche euch allen ein Frohes Neues Jahr', 'DANKE :)', 1, '42'),
(92, '2016-12-06 19:48:35', '2017-01-09 20:59:33', 'Thomas', 'Test', 'TestTestTestTestTestl', 'adgasg', 1, '34'),
(93, '2016-12-07 22:34:55', '2017-01-10 11:23:22', 'Maurice', 'Kicker', 'Hey, wie wäre es wenn wir uns mal einen Kicker für den Flur besorgen?', 'Nice-To-Have', 1, '2'),
(94, '2016-12-18 17:54:07', '2017-01-11 13:23:45', 'Patrick', 'Neue Möbel', 'Ich wäre mal für vernünftige Möbel', 'Maurice: Nee, lieber einen neuen Kühlschrank.; Thomas: Ich hätte lieber einen Beamer um mir Filme an zu gucken', 1, '64'),
(95, '2017-01-02 14:55:35', '2017-01-09 20:59:33', 'Stefan', 'PHP', 'I love PHP', 'Glückwunsch', 0, '88'),
(96, '2017-01-09 19:02:28', '2017-01-09 19:03:09', 'Thomas', 'Mehr Kaffee', 'Kaffee ist ein schwarzes, psychotropes, koffeinhaltiges Heißgetränk, das aus gerösteten und gemahlenen Kaffeebohnen, den Samen aus den Früchten der Kaffeepflanze, und heißem Wasser hergestellt wird.', '', 0, '2'),
(97, '2017-01-09 19:48:35', '2017-01-09 20:59:33', 'Thomas', 'Maler-App', 'Schönen Guten Morgen. Lasst uns eine App Entwickelt, die Malern unter die Arme greift.', 'Tim: Ich bin dabei', 0, '15'),
(98, '2017-01-09 21:00:17', NULL, 'Thomas', 'Lorem ipsum dolor sit amet', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.', NULL, NULL, '1'),
(99, '2017-01-11 10:48:35', '2017-01-11 23:59:33', 'Tim', 'Wackelpudding', 'Ich fände es Innovativ, wenn wir ab nächster Woche täglich Wackelpudding verteilen würden.', 'Stefan: Ich halte da nix von, dann schmeißen wir nur das Geld zum Fenster raus.', 0, '200'),
(100, '2017-01-12 19:48:35', '2017-01-13 20:59:33', 'Stefan', 'Prüfung', 'Hallo, ich wollte euch nur mitteilen, dass Ihr alle bestanden habt.', 'Tim:Bestanden; Maurice: Puuh, geschafft; Patrick: Bazinga; Thomas: Endlich und auf in die Nächste Prüfung', 1, '22');

--
-- Indizes der exportierten Tabellen
--

--
-- Indizes für die Tabelle `idea`
--
ALTER TABLE `idea`
  ADD KEY `ID` (`ID`);

--
-- AUTO_INCREMENT für exportierte Tabellen
--

--
-- AUTO_INCREMENT für Tabelle `idea`
--
ALTER TABLE `idea`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=101;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
